version: "3"

services:

  mautic:
    container_name: mautic
    image: mautic/mautic:latest
    volumes:
      - mautic_data:/var/www/html
      - .:/var/www/html/plugins/MauticSmsapiBundle
    environment:
      - MAUTIC_DB_HOST=database
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=mypassword
      - MAUTIC_DB_NAME=mautic3
    restart: always
    networks:
      - mauticnet
    ports:
      - "8880:80"

  database:
    image: powertic/percona-docker
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    restart: always
    networks:
      - mauticnet
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql-mode=""


volumes:
  mautic_data:
  database:

networks:
  mauticnet:
